pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir("ab-inbev_app"){
                    sh 'mvn clean install -DskipTests'
                }
            }
        }
        stage('Test') {
            steps {
                dir("ab-inbev_app"){
                    sh 'mvn test'
                }
            }
        }
        stage('Build Image') {
            steps {
                dir("ab-inbev_app"){
                    script {
                        def pom = readMavenPom file: "pom.xml"
                        sh "mvn spring-boot:build-image -Dspring-boot.build-image.imageName=rssarto/${pom.artifactId}:${pom.version} -DskipTests"
                    }
                }
            }
        }
        stage('Push Image'){
            steps {
                script {
                    def pom = readMavenPom file: "pom.xml"
                    docker.withRegistry('https://index.docker.io/v1/', 'dc3ecd62-cae0-4015-bc8e-03b2fef1f13c') {
                        def customImage = docker.image("rssarto/${pom.artifactId}:${pom.version}")
                        customImage.push()
                        sh "docker rmi rssarto/${pom.artifactId}:${pom.version}"
                    }
                }
            }
        }
    }
}